### ISSUE TITLE
What is your version of 'mlxtend' library in FinalModel.py ?

### ISSUE THREAD

**Issue by kwonsye** [jigawhat/MusicERS#2]
Hello, I want to run your code..
But mlxtend's version is not matched.
So I want to know your version. 
Let me know it soon. Thank you :)

**Comment by jigawhat** [comment]
Hey, I'm not sure which version I had installed originally but I think the newest version should work fine (0.13.0)

**Comment by jigawhat** [comment]
Ok I actually just saw what the problem was, the code was for an older version and I hadn't noticed the update. I've fixed the bug and added the working mlxtend version to requirements.txt (0.13.0). Please pull the changes! I'll add the versions of the other packages too.

**Comment by kwonsye** [comment]
Thank you! now it works!
